/*
  # Ajout de 25 propriétés de démonstration réalistes

  1. Contenu
    - 8 propriétés Cocody (haut standing) 280k-1200k
    - 5 propriétés Marcory (résidentiel) 120k-550k
    - 4 propriétés Yopougon (accessible) 100k-380k
    - 4 propriétés Plateau (affaires) 200k-600k
    - 4 autres quartiers 200k-700k
    
  2. Types de propriétés valides
    - appartement, villa, studio, bureau, commerce, chambre
*/

INSERT INTO properties (
  title, description, monthly_rent, deposit_amount, city, neighborhood, address,
  latitude, longitude, property_type, bedrooms, bathrooms, surface_area,
  has_parking, is_furnished, has_ac, has_garden, status, images
) VALUES
-- COCODY (8 propriétés)
('Villa Luxueuse Riviera Golf', 'Magnifique villa de prestige avec 5 chambres spacieuses, suite parentale avec dressing. Cuisine haut de gamme, salon avec cheminée. Jardin paysager avec piscine chauffée. Sécurité 24/7, domotique complète.', 900000, 1800000, 'Abidjan', 'Cocody', 'Riviera Golf', 5.3599, -3.9870, 'villa', 5, 4, 350, true, true, true, true, 'disponible', ARRAY['/images/hero-villa-cocody.jpg', '/images/hero-residence-moderne.jpg']),
('Appartement Standing 2 Plateaux', 'Superbe appartement 4 pièces résidence sécurisée. Salon lumineux, cuisine américaine moderne équipée, 3 chambres climatisées avec placards. Balcon spacieux, parking souterrain. Ascenseur, gardiennage 24/7.', 550000, 1100000, 'Abidjan', 'Cocody', '2 Plateaux Vallon', 5.3520, -3.9920, 'appartement', 3, 2, 120, true, true, true, false, 'disponible', ARRAY['/images/hero-immeuble-moderne.png', '/images/hero-residence-securisee.jpg']),
('Appartement Duplex Angré 8ème', 'Magnifique duplex neuf quartier prisé. Vaste séjour, cuisine équipée. 3 chambres avec salle de bain, suite parentale. Terrasse panoramique, climatisation centralisée. Résidence avec piscine commune et salle de sport.', 650000, 1300000, 'Abidjan', 'Cocody', 'Angré 8ème Tranche', 5.3780, -3.9950, 'appartement', 3, 3, 180, true, true, true, false, 'disponible', ARRAY['/images/hero-maison-moderne.jpg', '/images/hero-residence-moderne.jpg']),
('Studio Meublé Riviera Palmeraie', 'Charmant studio tout confort résidence calme. Espace optimisé coin nuit séparé, kitchenette équipée. Climatisé, WiFi haut débit inclus. Parfait jeune professionnel ou étudiant. Sécurité 24/7.', 280000, 560000, 'Abidjan', 'Cocody', 'Riviera Palmeraie', 5.3650, -3.9800, 'studio', 1, 1, 35, true, true, true, false, 'disponible', ARRAY['/images/hero-immeuble-moderne.png']),
('Villa Exceptionnelle Vallon', 'Propriété exception quartier huppé. 6 chambres sur 600m² terrain arboré. Architecture contemporaine. Grand séjour cathédrale, cuisine premium, salle de cinéma. Piscine à débordement, pool house, tennis.', 1200000, 2400000, 'Abidjan', 'Cocody', 'Vallon', 5.3480, -3.9850, 'villa', 6, 5, 500, true, true, true, true, 'disponible', ARRAY['/images/hero-villa-cocody.jpg', '/images/hero-residence-moderne.jpg']),
('Appartement Standing Riviera Golf', 'Élégant appartement 3 pièces immeuble moderne. Séjour spacieux baie vitrée, cuisine îlot central, 2 chambres placards. Terrasse vue golf. Marbre, parquet, domotique. Piscine résidence.', 480000, 960000, 'Abidjan', 'Cocody', 'Riviera Golf', 5.3610, -3.9880, 'appartement', 2, 2, 110, true, true, true, false, 'disponible', ARRAY['/images/hero-residence-moderne.jpg']),
('Appartement Prestige Angré', 'Somptueux appartement dernier étage résidence luxe. 4 chambres en suite, salon panoramique, cuisine italienne. Immense terrasse 80m² avec jacuzzi vue 360°. Domotique complète. 3 parkings privés. Ascenseur privatif.', 850000, 1700000, 'Abidjan', 'Cocody', 'Angré 8ème', 5.3790, -3.9960, 'appartement', 4, 4, 250, true, true, true, false, 'disponible', ARRAY['/images/hero-immeuble-moderne.png', '/images/hero-residence-moderne.jpg']),
('Appartement Moderne Ambassades', 'Bel appartement 2 pièces quartier Ambassades. Séjour lumineux, cuisine américaine, 1 chambre spacieuse. Balcon, climatisation, fibre optique. Immeuble récent ascenseur. Quartier calme.', 400000, 800000, 'Abidjan', 'Cocody', 'Ambassades', 5.3550, -3.9900, 'appartement', 1, 1, 75, true, true, true, false, 'disponible', ARRAY['/images/hero-residence-moderne.jpg']),

-- MARCORY (5 propriétés)
('Appartement Familial Zone 4', 'Grand appartement 4 pièces Zone 4. Spacieux séjour-salle à manger, cuisine coin repas, 3 chambres, 2 salles eau. Balcons, ventilateurs, placards. Gardien permanent. Quartier résidentiel calme, écoles proches.', 320000, 640000, 'Abidjan', 'Marcory', 'Zone 4', 5.3100, -4.0000, 'appartement', 3, 2, 110, true, false, true, false, 'disponible', ARRAY['/images/hero-quartiers-abidjan.jpg', '/images/hero-residence-securisee.jpg']),
('Villa Contemporaine Zone 4C', 'Belle villa moderne quartier résidentiel. 4 chambres climatisées dont suite parentale, salon-salle à manger, cuisine équipée. Véranda, jardin arboré. Garage double. Citerne eau, groupe électrogène. Portail électrique.', 550000, 1100000, 'Abidjan', 'Marcory', 'Zone 4C', 5.3050, -4.0050, 'villa', 4, 3, 200, true, false, true, true, 'disponible', ARRAY['/images/hero-maison-moderne.jpg', '/images/hero-residence-moderne.jpg']),
('Studio Étudiant Biétry', 'Studio simple fonctionnel Biétry, idéal étudiant. Pièce principale kitchenette intégrée, salle eau. Meublé : lit, bureau, armoire. Ventilateur. Immeuble propre gardien. Quartier vivant, gares proches. Loyer abordable.', 120000, 240000, 'Abidjan', 'Marcory', 'Biétry', 5.3180, -3.9950, 'studio', 1, 1, 25, false, true, false, false, 'disponible', ARRAY['/images/hero-logements-sociaux.jpg']),
('Appartement Standing Remblais', 'Superbe appartement duplex résidence moderne. RDC : séjour lumineux, salle à manger, cuisine américaine. Étage : 3 chambres climatisées placards, 2 salles de bain. Balcon et terrasse. Résidence piscine, aire jeux, gardiennage 24/7.', 400000, 800000, 'Abidjan', 'Marcory', 'Remblais', 5.3150, -3.9920, 'appartement', 3, 2, 140, true, false, true, false, 'disponible', ARRAY['/images/hero-residence-moderne.jpg', '/images/hero-residence-securisee.jpg']),
('Appartement Confortable Zone 3', 'Appartement 2 pièces bien situé Zone 3. Salon, cuisine séparée, 1 grande chambre, salle de bain. Carrelage, peinture récente. Climatiseur chambre. Immeuble gardien jour. Quartier dynamique, marchés à pied.', 250000, 500000, 'Abidjan', 'Marcory', 'Zone 3', 5.3120, -3.9980, 'appartement', 1, 1, 65, true, false, true, false, 'disponible', ARRAY['/images/hero-quartiers-abidjan.jpg']),

-- YOPOUGON (4 propriétés)
('Appartement Moderne Siporex', 'Appartement 3 pièces résidence récente Siporex. Séjour coin repas, cuisine carrelée, 2 chambres ventilateurs, douche moderne. Balcon, eau courante. Immeuble propre concierge. Quartier développement, commerces, écoles.', 180000, 360000, 'Abidjan', 'Yopougon', 'Siporex', 5.3450, -4.0850, 'appartement', 2, 1, 75, true, false, false, false, 'disponible', ARRAY['/images/hero-quartiers-abidjan.jpg', '/images/hero-logements-sociaux.jpg']),
('Villa Familiale Niangon', 'Grande villa familiale Niangon. 5 chambres spacieuses, 2 salons, cuisine traditionnelle et externe, 3 salles eau. Garage, cour, véranda. Grande citerne, installation solaire. Mur enceinte. Quartier organisé, marché, écoles proches.', 380000, 760000, 'Abidjan', 'Yopougon', 'Niangon', 5.3500, -4.0900, 'villa', 5, 3, 180, true, false, true, true, 'disponible', ARRAY['/images/hero-quartier-construction.jpg', '/images/hero-maison-moderne.jpg']),
('Studio Pratique Selmer', 'Studio fonctionnel Selmer budget limité. Chambre-salon coin cuisine, douche WC. Ventilateur, moustiquaire. Compteurs individuels. Immeuble simple propre. Gardien nuit. Bien situé : gare, marché dans rue. Jeune travailleur ou étudiant.', 100000, 200000, 'Abidjan', 'Yopougon', 'Selmer', 5.3400, -4.0800, 'studio', 1, 1, 28, false, false, false, false, 'disponible', ARRAY['/images/hero-logements-sociaux.jpg']),
('Appartement 2 Pièces Port-Bouët', 'Appartement simple 2 pièces Yopougon Port-Bouët. Salon, cuisine, 1 chambre, douche interne. Carrelage simple, peinture propre. Eau SODECI, électricité CIE. Immeuble R+2 concierge jour. Quartier animé, transport abondant. Loyer abordable.', 150000, 300000, 'Abidjan', 'Yopougon', 'Port-Bouët II', 5.3350, -4.0700, 'appartement', 1, 1, 55, false, false, false, false, 'disponible', ARRAY['/images/hero-quartiers-abidjan.jpg']),

-- PLATEAU (4 propriétés)
('Bureau Standing Plateau', 'Espace bureau 120m² immeuble standing. Open space lumineux, 2 bureaux fermés, salle réunion équipée, kitchenette. Climatisation centralisée, fibre optique, groupe électrogène. Réception, sécurité 24/7, ascenseurs. Parking souterrain.', 600000, 1200000, 'Abidjan', 'Plateau', 'Boulevard Clozel', 5.3253, -4.0233, 'bureau', 0, 2, 120, true, true, true, false, 'disponible', ARRAY['/images/hero-immeuble-moderne.png']),
('Studio Fonctionnel Ministères', 'Studio pratique professionnel Plateau. Espace vie coin nuit, kitchenette, salle eau. Meublé équipé : lit, bureau, réfrigérateur. Climatisé, WiFi inclus. Immeuble sécurisé gardiennage. 5 minutes ministères. Charges incluses.', 200000, 400000, 'Abidjan', 'Plateau', 'Rue des Jardins', 5.3280, -4.0210, 'studio', 1, 1, 30, true, true, true, false, 'disponible', ARRAY['/images/hero-residence-moderne.jpg']),
('Appartement Rénové 3 Pièces', 'Appartement entièrement rénové cœur Plateau. Séjour climatisé, cuisine équipée neuve, 2 chambres placards, salle de bain moderne. Peinture fraîche, carrelage partout. Immeuble ascenseur gardien. Générateur. Quartier animé commerces restaurants.', 380000, 760000, 'Abidjan', 'Plateau', 'Avenue Chardy', 5.3260, -4.0220, 'appartement', 2, 1, 85, true, false, true, false, 'disponible', ARRAY['/images/hero-quartiers-abidjan.jpg']),
('Local Commercial Avenue', 'Espace commercial stratégique avenue passante. 80m² vitrine, salle principale, arrière-boutique, WC. Climatisation, compteur séparé. Idéal boutique, agence, cabinet, showroom. Visibilité maximale, passage piéton important.', 450000, 900000, 'Abidjan', 'Plateau', 'Avenue Franchet d''Esperey', 5.3240, -4.0250, 'commerce', 0, 1, 80, true, false, true, false, 'disponible', ARRAY['/images/hero-immeuble-moderne.png']),

-- AUTRES QUARTIERS (4 propriétés)
('Villa Vue Mer Grand-Bassam', 'Magnifique villa pieds dans eau Grand-Bassam. 4 chambres climatisées vue océan, vaste séjour ouvert terrasse, cuisine équipée. Jardin tropical direct plage privée. Piscine à débordement, pool house barbecue. Gardiennage permanent. Cadre idyllique.', 700000, 1400000, 'Grand-Bassam', 'Phare', 'Front de mer', 5.2089, -3.7386, 'villa', 4, 3, 220, true, true, true, true, 'disponible', ARRAY['/images/hero-villa-cocody.jpg', '/images/hero-residence-moderne.jpg']),
('Appartement Moderne Koumassi', 'Bel appartement 3 pièces résidence moderne Koumassi. Salon lumineux, cuisine aménagée, 2 chambres placards, salle de bain complète. Climatisation, balcon. Résidence ascenseur, gardiennage continu, parking sécurisé. Générateur central.', 220000, 440000, 'Abidjan', 'Koumassi', 'Koumassi Remblais', 5.2950, -3.9450, 'appartement', 2, 1, 80, true, false, true, false, 'disponible', ARRAY['/images/hero-residence-moderne.jpg']),
('Villa Résidentielle Bingerville', 'Charmante villa quartier calme Bingerville. 4 chambres confortables, salon-salle à manger, cuisine spacieuse, bureau. Véranda couverte, jardin fleuri, garage. Installation solaire complète, grande citerne. Environnement paisible verdoyant. Écoles réputées.', 520000, 1040000, 'Bingerville', 'Centre', 'Boulevard Gbon Coulibaly', 5.3553, -3.9090, 'villa', 4, 2, 170, true, false, true, true, 'disponible', ARRAY['/images/hero-maison-moderne.jpg', '/images/hero-quartier-construction.jpg']),
('Appartement Duplex Abobo Gare', 'Duplex pratique près gare Abobo. Niveau 1 : séjour, cuisine, WC. Niveau 2 : 2 chambres, salle de bain. Carrelage partout, peinture récente. Ventilateurs, moustiquaires. Immeuble gardien. Situation stratégique : gare, marché, écoles 5min pied. Transport abondant.', 200000, 400000, 'Abidjan', 'Abobo', 'Abobo Gare', 5.4283, -4.0267, 'appartement', 2, 1, 90, true, false, false, false, 'disponible', ARRAY['/images/hero-quartiers-abidjan.jpg']);