// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env['VITE_SUPABASE_URL'] ?? '';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env['VITE_SUPABASE_PUBLISHABLE_KEY'] ?? '';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create client only if env vars are available, otherwise create a placeholder
function createSafeClient(): SupabaseClient<Database> {
  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    console.warn('[Supabase] Environment variables not configured. Using placeholder client.');
    // Return a minimal proxy that won't throw immediately
    // Real functionality comes from @/services/supabase/client
    return new Proxy({} as SupabaseClient<Database>, {
      get: (_target, prop) => {
        if (prop === 'auth') {
          return {
            getSession: () => Promise.resolve({ data: { session: null }, error: null }),
            onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
            signInWithPassword: () => Promise.resolve({ data: { user: null, session: null }, error: { message: 'Supabase not configured' } }),
            signUp: () => Promise.resolve({ data: { user: null, session: null }, error: { message: 'Supabase not configured' } }),
            signOut: () => Promise.resolve({ error: null }),
          };
        }
        if (prop === 'from') {
          const chainable = {
            select: () => chainable,
            eq: () => chainable,
            neq: () => chainable,
            in: () => chainable,
            is: () => chainable,
            gt: () => chainable,
            gte: () => chainable,
            lt: () => chainable,
            lte: () => chainable,
            like: () => chainable,
            ilike: () => chainable,
            order: () => chainable,
            limit: () => chainable,
            range: () => chainable,
            single: () => Promise.resolve({ data: null, error: { message: 'Supabase not configured' } }),
            maybeSingle: () => Promise.resolve({ data: null, error: { message: 'Supabase not configured' } }),
            insert: () => Promise.resolve({ data: null, error: { message: 'Supabase not configured' } }),
            update: () => chainable,
            delete: () => chainable,
            upsert: () => Promise.resolve({ data: null, error: { message: 'Supabase not configured' } }),
            then: (resolve: (value: { data: null; error: { message: string } }) => void) => 
              resolve({ data: null, error: { message: 'Supabase not configured' } }),
          };
          return () => chainable;
        }
        if (prop === 'functions') {
          return {
            invoke: () => Promise.resolve({ data: null, error: { message: 'Supabase not configured' } }),
          };
        }
        if (prop === 'rpc') {
          return () => Promise.resolve({ data: null, error: { message: 'Supabase not configured' } });
        }
        return undefined;
      },
    });
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

export const supabase = createSafeClient();
