// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const env = import.meta.env;
const SUPABASE_URL = env.VITE_SUPABASE_URL || env.VITE_PUBLIC_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  env.VITE_SUPABASE_ANON_KEY ||
  env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  env.VITE_PUBLIC_SUPABASE_ANON_KEY ||
  env.VITE_PUBLIC_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    'Supabase configuration is missing. Please set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY.'
  );
}

// Aggressive token cleanup - remove all Supabase auth data
const aggressiveTokenCleanup = () => {
  try {
    // Remove all possible Supabase auth keys
    const keysToRemove = [];
    for (let i = 0; i < localStorage.length; i++) {
      const key = localStorage.key(i);
      if (key && (key.includes('supabase') || key.includes('auth'))) {
        keysToRemove.push(key);
      }
    }
    keysToRemove.forEach((key) => {
      try {
        localStorage.removeItem(key);
      } catch (e) {
        // Ignore individual removal errors
      }
    });
    console.log('Cleaned up', keysToRemove.length, 'Supabase/auth items from localStorage');
  } catch (error) {
    console.warn('Could not perform aggressive token cleanup:', error);
  }
};

// Check if we need to clean tokens (run on every load)
const shouldCleanTokens = () => {
  try {
    // Check for any suspicious tokens, but allow Supabase dev keys
    for (let i = 0; i < localStorage.length; i++) {
      const key = localStorage.key(i);
      if (key && key.includes('supabase')) {
        const value = localStorage.getItem(key);
        if (
          value &&
          // Clean obvious invalid tokens
          (value.length < 10 ||
            value === 'null' ||
            value === 'undefined' ||
            // But allow valid Supabase tokens that start with 'ey' or 'sb_publishable'
            (!value.startsWith('ey') && !value.startsWith('sb_publishable') && value.length < 50))
        ) {
          return true;
        }
      }
    }
    return false;
  } catch (error) {
    return true; // If in doubt, clean
  }
};

// Export the Supabase URL for use in other configurations
export const SUPABASE_API_URL = SUPABASE_URL;

// Function to get session without circular dependency
const getSession = () => {
  try {
    // Supabase stores the session in a project-scoped key: sb-<project-ref>-auth-token
    const projectRef = (() => {
      try {
        return new URL(SUPABASE_URL).hostname.split('.')[0];
      } catch {
        return null;
      }
    })();
    const keys = [
      projectRef ? `sb-${projectRef}-auth-token` : null,
      'supabase.auth.token',
      'sb-auth-token',
      'supabase.auth',
    ].filter(Boolean) as string[];

    const parseSession = (raw: string) => {
      try {
        const data = JSON.parse(raw);
        if (data?.currentSession?.access_token) return data.currentSession;
        if (data?.access_token) return data;
        if (Array.isArray(data)) {
          const found = data.find((item) => item?.access_token);
          if (found) return found;
        }
      } catch {
        // Ignore parse errors and continue
      }
      return null;
    };

    for (const key of keys) {
      const sessionStr = localStorage.getItem(key);
      if (!sessionStr) continue;

      const session = parseSession(sessionStr);
      if (session) return session;
    }
  } catch (e) {
    // Ignore errors
  }
  return null;
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
  global: {
    headers: {
      'x-connect-timeout': '30s',
      'x-read-timeout': '60s',
    },
    // Custom fetch to handle Authorization header correctly
    fetch: (url, options = {}) => {
      // Check if user is logged in
      const session = getSession();

      if (!session) {
        // Remove Authorization header for public requests
        const newOptions = { ...options };
        if (newOptions.headers) {
          const headers = { ...newOptions.headers } as Record<string, string>;
          delete headers['Authorization'];
          newOptions.headers = headers;
        }
        return fetch(url, newOptions);
      }

      return fetch(url, options);
    },
  },
  db: {
    schema: 'public',
  },
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
});

// Handle auth errors more gracefully
supabase.auth.onAuthStateChange((event, session) => {
  // Only perform cleanup on actual sign out, not on token refresh
  if (event === 'SIGNED_OUT' && !session) {
    console.log('User signed out, performing token cleanup');
    aggressiveTokenCleanup();
  }
});
